### PR TITLE
Fixing wrong sequences of two apostrophe characters in the French

### PR DESCRIPTION
**Pull request by zx-fulvio**
localization.

Same sort of fix as in  [this pull request](https://github.com/Zimbra/zm-web-client/pull/99)

### CODE REVIEW

**Comment by zx-fulvio** [comment]
Referenced [here](https://github.com/Zimbra/zm-web-client/pull/99)

**Comment by zx-fulvio** [comment]
@silentsakky @mihaipopahtp This I think should be applied/merged before applying the global modifications mentioned in [this pull request](https://github.com/Zimbra/zm-web-client/pull/115).
Just to avoid doubling smart quotes too by mistake :-) .

**Comment by mihaipopahtp** [comment]
@zx-fulvio, @silentsakky 
To add a bit of detail to what I am doing and ask for some of your cents on this:

What I've done:
1. I made a compound out of all existing .properties and used a script to tag all the translatable text (so I won't change anything that's within code, URLs and so on).
2. I "undoubled" all existing apostrophes and "smart quotes" within the translatable text.
3. replaced all apostrophes with smartquotes inside the translatable text.
4. isolated keys that have instances such as "Enable the ‘Email Quotes’ Zimlet", where I need to replace the first smart (\u2019) quote with an opening quote (\u2018). (I only need to check this in English and I will propagate it as a rule on all languages). 

I was hoping to finalize this today, but there are instances such as:
"formatWordyDateYesterday = 'Yesterday,' h:mm" where the apostrophes need to be kept, so I have to double check these and revert them where necessary.
And also, in some instances the linguist replaced opening and closing apostrophes with native quotes, so I will have to do that to keep things consistent within those languages.
This is taking me a bit longer than I expected, but after this is done, all visible apostrophes will be replaced with smart quotes (\u2019) or the \u2018 \u2019 pair (or native quotes), where necessary, so everything would be consistent.

There might be some back and forth on Arabic and Hebrew, since I don't know how the \u2018 \u2019 pair will be displayed and some bidi markers might be needed, but for the other languages this should be fine.

If you see anything wrong in this process, please let me know.

**Comment by zx-fulvio** [comment]
@mihaipopahtp 
I am not entirely sure I understood the tagging bit at point 1. Could you elaborate a bit?
Talking about ZM_formatVoiceDateYesterday, which is in the zm-web-client repository and I think might be the key you are referring to (as it holds the same value), I see that the code has a line [which apparently removes the apostrophes altogether](https://github.com/Zimbra/zm-web-client/blob/926f8e264441c83fb8d0c70fe47dba71a4bfaa84/WebRoot/h/printvoicemails#L161).
There's an function called insert in the same two files that resource (and related ones ) is mentioned which uses the apostrophe as an escape character while doing some templating with timestamps.
Frankly given how limited the scope is I'd suggest modifying the function to use a different escape character (even a double quote as far as I am concerned) and get rid of the apostrophe, rather than complicating everything else and drag along the issue. Do you have other problematic and unrelated keys, maybe in different repositories?
Native quotes are of course better where available.
I was uncertain too about RTL languages, but just substituting the .properties file on a test system and rebooting the web component might give you an answer. I could try having the web interface output a known key with the new text on a test system to check it out once you have a sample (or just pluggin an enclosed string inside a known key merely as a test).
Talking about consistency, translators seem to have used interchangeably apostrophes and double quotes around in many places when it came to enclose bits of text (i.e. in the situation of point 4). Not sure whether you'd like to replace double quotes too.

**Comment by mihaipopahtp** [comment]
@zx-fulvio 

on the tagging part:
I basically ended up making a big word file per language, in which the code and translatable text use different styles.
Then with the help of regular expressions and some scripts I'm trying to make sure that a general replacement of the apostrophes, depending on the styles in which they are written, will only replace the correct ones, so I will only need to double check that the replacements are correct.

on apostrophes used as an escape character:
I am trying to avoid changing any files other than the ones that are used for localization because I don't know the implications such a change might have. I see your point and agree with you, but I'm not qualified to go outside the localizable files :).
The scope is limited indeed. There are only a few strings in this situation, so it was easier for me to revert or skip them during replacement than going through the code. 
formatWordyDateToday = formatWordyDateToday = 'Today,' h:mm a
fontFamilyBase2.css = 'times new roman', 'new york', times, serif
fontFamilyBase3.css = 'arial black','avant garde'
fontFamilyBase4.css = 'courier new', courier, monaco, monospace, sans-serif
fontFamilyBase5.css = 'comic sans ms', 'comic sans', sans-serif
fontFamilyBase6.css = 'lucida console', sans-serif
fontFamilyBase7.css = garamond, 'new york', times, serif
fontFamilyBase9.css = tahoma, 'new york', times, serif
fontFamilyBase11.css = 'trebuchet ms',sans-serif

I am still looking into point 4.
I have a script to check the pairing of quotes and I will replace at least some of the straight quotes with native ones as well. I think some were left as straight quotes instead of native because they were written as &quot; and left as is. I'm trying to make this consistent while I'm at it.

**Comment by zx-fulvio** [comment]
@mihaipopahtp 
Did you also find ZM_formatVoiceDateYesterday and similar? You haven't mentioned those but they have the same sort of values.
About formatWordyDateToday, can you tell which repository it's used in?
When you mentioned "code and translatable text", what do you mean by code? Do you have a sample?
About the problem keys, I think we might as well skip those for now. Once identified the repositories they belong to I might take a look at the code and see whether a quick fix is feasible. Then fix code AND strings together as a second step. Or not if that's not feasible.

**Comment by mihaipopahtp** [comment]
@zx-fulvio 

found them, yes. Please see the repos for each below:
GitHub\zm-admin-ajax\WebRoot\messages\AjxMsg.properties
formatWordyDateToday = ’Today,’ h:mm a
formatWordyDateYesterday = ’Yesterday,’ h:mm a

GitHub\zm-ajax\WebRoot\messages\AjxMsg.properties
formatWordyDateToday = ’Today,’ h:mm a
formatWordyDateYesterday = ’Yesterday,’ h:mm a

GitHub\zm-web-client\WebRoot\messages\ZhMsg.properties
ZM_formatVoiceDateToday = ’Today,’ h:mm a
ZM_formatVoiceDateYesterday = ’Yesterday,’ h:mm a

I don't know if you have access to the Stash repos. I'm attaching a compound of all used US properties, in case you find it helpful. It eases the search.
[$all_US.txt](https://github.com/Zimbra/zm-admin-console/files/1241222/all_US.txt)
I have one for each language if you need any other.


On the code vs translatable text part - that's something out of the localization point of view. Sorry for the confusion.
Everything that's not translatable and we don't want to modify is considered "code". That includes key names, formatting tags, urls, placeholders, comments and so on. I just tagged them in a different manner so I can ignore them and make sure they are not changed.

**Comment by zx-fulvio** [comment]
@mihaipopahtp 
Uncertain about the key calendarResourceConflictDateTimeFormat in the BitBucket repos.
Bit of a problem in your distinction between translatable text and code. URLs for instance in some cases have element attributes enclosed by single quotes. That's a potential problem if that url is a format string because those apostrophes will be removed after processing. Double quotes would be the best option there IMO. So, untranslatable but still in need of a look.
For instance
`BNR_AddPrefix = Add prefix <span class='ZaHighlightedText'>{0}</span> to each restored account`
Looking at the code handling timestamps format, it might be better to leave apostrophes there (since they actually are there to escape something). Not sure about the fontFamilyBaseX.css keys.
At this point I'd just leave the timestamp formats as they are and go ahead with everything else, in order to have something to verify and test.

**Comment by mihaipopahtp** [comment]
@zx-fulvio 

calendarResourceConflictDateTimeFormat:
I initially changed those with \u2018-\u2019, but now that you mentioned it I really think I need to revert it to straight apostrophes.

distinction between "code" vs traslatable:
I marked what's between  \<*\></*> is in a different style (it's treated as "code") so these won't be changed in any way while I replace the apostrophes from the translatable text. 

fontFamilyBaseX.css keys:
These are in a "#L10N_IGNORE_BLOCK". I'm pretty sure I'm not suppose to change these.

**Comment by mihaipopahtp** [comment]
@zx-fulvio 

Some more instances of apostrophes used as an escape chars that I think need to be kept:

date/time format keys (there are several of these):
formatCalDateFull = EEEE, d MMMM 'de' yyyy
formatCalMonth = MMMM 'de' yyyy
in languages that use this type of date format (some latin languages e.g ca, pt, es) so the

**Comment by zx-fulvio** [comment]
@mihaipopahtp Yep, I think most time-related strings use apostrophes to preserve literal strings from interpolation/interpretation.

**Comment by silentsakky** [comment]
Will be fixed in https://github.com/Zimbra/zm-admin-console/pull/26

**Pull request closed without merging**
