### PR TITLE
ZCS-3103, ZCS-3104: Fixed removing rentry of DL 'Direct member of' on edit & saving reply-to address when set focus in the field

### PR DESCRIPTION
**Pull request by k-kato**
Fixed distribution list related issues.

### CODE REVIEW

**Comment by jiteshsojitra** [comment]
Hi Koichi,

Thanks for making the changes.

1. Can you please mention some regression areas which team can try because we are merging in develop?
2. Also please modify review request subject for e.g. ZCS-3103, ZCS-3104: <high level summary about the fixes>.

**Comment by k-kato** [comment]
@jiteshsojitra Thank you for your comment.
1. Could you let me know about "regression areas" you expect? Does it mean fields/pages/buttons the team needs to test?
2. changed the subject of the PR.

**Comment by jiteshsojitra** [comment]
@k-kato - Yes, mostly functional area to be tested which might have affected as far as this change is concerned.

**Comment by k-kato** [comment]
[Affected areas]
ZCS-3103:
- Page:   Home -> Manage -> Accounts -> account -> Member Of
  Action: remove member(s) from Direct Member Of and click Save
- Page:   Home -> Manage -> Distribution Lists -> dl -> Member Of
  Action: remove member(s) from Direct Member Of and click Save

ZCS-3104:
- Page/Field: New Distribution List -> Preferences -> Reply-to address
  Action: Enter an email and click Finish without moving a focus to anywhere else 
- Page/Field: Home -> Manage -> Distribution Lists -> Preferences -> Reply-to address
  Action: Enter an email and click Save without moving a focus to anywhere else

**Pull request merged**
